### ISSUE TITLE
Idk if you can chat but whatever

### ISSUE THREAD

**Issue by MickTheRus** [Setnour6/CraftableTreasureBags#1]
What issues are you having with recipe groups, are you checking if a mod is loaded?

**Comment by Setnour6** [comment]
> What issues are you having with recipe groups, are you checking if a mod is loaded?

I tried using recipe groups prior to release, and every time I use the recipe browser, or I see the crafting option appear, my game crashes. I didn't want the same to happen to everyone else. I don't even know much about recipe groups anyways when it comes to vanilla or modded recipes.
